# Generated by Django 5.1.6 on 2025-02-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0003_userprofile_email_company_userprofile_is_group'),
        ('property', '0066_commercial_commercial_decor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=12, verbose_name='chat_id')),
                ('send_keys', models.DateField(blank=True, null=True, verbose_name='Выдача ключей')),
                ('building', models.ManyToManyField(blank=True, to='property.buildings', verbose_name='building_id')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authapp.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Подписки telegram пользователей',
            },
        ),
    ]
