# Generated by Django 4.0 on 2024-09-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonStatistics',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('menu_button_1', models.IntegerField(default=0)),
                ('menu_button_2', models.IntegerField(default=0)),
                ('menu_button_3', models.IntegerField(default=0)),
                ('menu_button_4', models.IntegerField(default=0)),
                ('menu_button_5', models.IntegerField(default=0)),
                ('menu_button_6', models.IntegerField(default=0)),
                ('menu_button_7', models.IntegerField(default=0)),
                ('menu_button_8', models.IntegerField(default=0)),
                ('novostroiki_1', models.IntegerField(default=0)),
                ('commercial_1', models.IntegerField(default=0)),
                ('vtorichka_1', models.IntegerField(default=0)),
                ('est_vznos_3', models.IntegerField(default=0)),
                ('net_vznosa_3', models.IntegerField(default=0)),
                ('est_sertificat_3', models.IntegerField(default=0)),
                ('est_design_4', models.IntegerField(default=0)),
                ('nuzhen_design_4', models.IntegerField(default=0)),
                ('ne_nuzhen_design_4', models.IntegerField(default=0)),
                ('uzhe_bought_8', models.IntegerField(default=0)),
                ('sub_to_zhk_8', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Статистика по кнопкам',
            },
        ),
        migrations.CreateModel(
            name='TelegramUserData',
            fields=[
                ('telegram_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('subscribed_to_jk', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Статистика пользователей',
            },
        ),
    ]
