# Generated by Django 5.1.6 on 2025-03-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0003_userprofile_email_company_userprofile_is_group'),
        ('property', '0066_commercial_commercial_decor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='property.buildings', verbose_name='Дом')),
                ('photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='property.buildingphotos', verbose_name='Ссылка на фото')),
            ],
            options={
                'verbose_name_plural': 'Просмотренные фото',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=12, unique=True, verbose_name='Чат')),
                ('send_keys', models.DateField(blank=True, null=True, verbose_name='Выдача ключей')),
                ('is_registed', models.BooleanField(default=False, verbose_name='Зарегистрирован')),
                ('building', models.ManyToManyField(blank=True, to='property.buildings', verbose_name='Дом')),
                ('seen_photos', models.ManyToManyField(blank=True, to='bot.seenphoto', verbose_name='Просмотренные фото')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authapp.userprofile')),
            ],
            options={
                'verbose_name_plural': 'telegram пользователи',
            },
        ),
    ]
