# Generated by Django 5.1.3 on 2025-03-01 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_userprofile_google_url'),
        ('property', '0071_alter_buildingphotos_build_video'),
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='property.buildings', verbose_name='Дом')),
                ('photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='property.mainphotos', verbose_name='Ссылка на фото')),
            ],
            options={
                'verbose_name_plural': 'Просмотренные фото',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=12, unique=True, verbose_name='Чат')),
                ('send_keys', models.DateField(blank=True, null=True, verbose_name='Выдача ключей')),
                ('is_registed', models.BooleanField(default=False, verbose_name='Зарегистрирован')),
                ('building', models.ManyToManyField(blank=True, to='property.buildings', verbose_name='Дом')),
                ('seen_photos', models.ManyToManyField(blank=True, to='telegrambot.seenphoto', verbose_name='Просмотренные фото')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authapp.userprofile')),
            ],
            options={
                'verbose_name_plural': 'telegram пользователи',
            },
        ),
        migrations.DeleteModel(
            name='ButtonStatistics',
        ),
        migrations.DeleteModel(
            name='TelegramUserData',
        ),
    ]
