# Generated by Django 5.1.3 on 2025-03-09 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0071_alter_buildingphotos_build_video'),
        ('telegrambot', '0002_seenphoto_tguser_delete_buttonstatistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seenphoto',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='property.buildingphotos', verbose_name='Ссылка на фото'),
        ),
    ]
