# Generated by Django 5.1.3 on 2025-10-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_alter_seenphoto_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'ordering': ['id'], 'verbose_name_plural': 'telegram пользователи'},
        ),
    ]
